accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views
from .views import (DashboardView, _PasswordChangeView, _PasswordChangeDoneView, _PasswordResetView,
    _PasswordResetDoneView, _PasswordResetConfirmView, _PasswordResetCompleteView,
    CreateUser, UserCreated, UsersView, UpdateUser, UsersView)


urlpatterns = [
    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('sair/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('painel/', DashboardView.as_view(), name='dashboard'),
    path('alterar-senha/', _PasswordChangeView.as_view(), name='edit_password'),
    path('alterar-senha/senha-alterada-com-sucesso', _PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('nova-senha/', _PasswordResetView.as_view(), name='password_reset'),
    path('nova-senha/nova-senha-solicitada', _PasswordResetDoneView.as_view()),
    path('confirmar-nova-senha/<uidb64>/<token>', _PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirmar-nova-senha/<uidb64>/senha-redefinida-com-sucesso', _PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('novo-usuario/', CreateUser.as_view(), name='new_user'),
    path('novo-usuario/usuario-inserido-com-sucesso', UserCreated.as_view()),
    path('atualizar-usuario/<int:pk>/', UpdateUser, name='update_user'),
    path('usuarios/', UsersView.as_view(), name='users'),
 ]

campus_app/urls.py
from django.urls import path
from .views import HomeView, NoticiaCreate, NoticiaView, NoticiaUpdate, NoticiaDelete, NoticiaDataView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('noticia_archive_day/<int:year>/<int:month>/<int:day>', NoticiaDataView.as_view(month_format='%m'),
         name='noticia_data'),
    path('noticia_list/', NoticiaView.as_view(), name='noticia_list'),
    path('noticia_create_form/', NoticiaCreate.as_view(), name='noticia_create_form'),
    path('noticia_update_form/<int:pk>', NoticiaUpdate.as_view(), name='noticia_update_form'),
    path('noticia_confirm_delete/<int:pk>', NoticiaDelete.as_view(), name='noticia_confirm_delete'),
]

campus_online/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('campus_app.urls')),
    path('', include('accounts.urls')),
    path('', include('pwa.urls')),
]

campus_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Noticia(models.Model):
    usuarios = models.ManyToManyField(User, related_name="usuario_noticia")
    titulo = models.CharField(max_length=200)
    palavras_chave = models.CharField(max_length=200, null=True, blank=True, default='')
    resumo = models.CharField(max_length=300, null=True, blank=True, default='')
    texto = models.TextField(max_length=600)
    prioridade = models.IntegerField(default=0)
    link_externo = models.CharField(max_length=300, null=True, blank=True, default='')
    link_foto = models.CharField(max_length=300, null=True, blank=True, default='')
    link_audio = models.CharField(max_length=300, null=True, blank=True, default='')
    link_video = models.CharField(max_length=300, null=True, blank=True, default='')
    link_georreferenciamento = models.CharField(max_length=300, null=True, blank=True, default='')
    data_publicacao = models.DateTimeField(auto_now_add=True)
    dia_publicacao = models.DateField(auto_now_add=True)

campus_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Noticia
from django.contrib.auth.models import User

class NoticiaForm(forms.ModelForm):
    usuarios = forms.ModelMultipleChoiceField(
            widget=forms.CheckboxSelectMultiple,
            queryset=User.objects.all().order_by('first_name'),
            required=True)
    class Meta:
        model = Noticia
        fields = ['usuarios', 'titulo', 'texto', 'prioridade',
                  'link_externo', 'link_video', 'link_foto']

campus_app/views.py
from django.urls import reverse_lazy
from .models import Noticia
from django.contrib.auth.models import Group
from .forms import NoticiaForm
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, DeleteView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.dates import DayArchiveView
import datetime


class HomeView(TemplateView):
    template_name = "campus_app/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['noticias'] = Noticia.objects.order_by('-dia_publicacao', '-prioridade', '-data_publicacao')[:20]
        context['data'] = datetime.date.today() 
                
        return context


class NoticiaDataView(DayArchiveView):
    queryset = Noticia.objects.order_by('-dia_publicacao', '-prioridade', '-data_publicacao')
    date_field = "dia_publicacao"
    allow_future = False
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['noticias'] = self.queryset
        context['data'] = datetime.date(self.get_year(), self.get_month(), self.get_day())

        return context


class NoticiaView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = 'campus_app.view_noticia'
    template_name = "campus_app/noticia_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['noticias'] = Noticia.objects.order_by('-data_publicacao').all
        context['perfil'] = Group.objects.filter(user = self.request.user)
        return context

      
class NoticiaCreate(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    permission_required = 'campus_app.add_noticia'
    template_name = 'campus_app/noticia_form.html'
    form_class = NoticiaForm
    success_url = reverse_lazy('noticia_list')
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class NoticiaUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'campus_app.change_noticia'
    model = Noticia
    fields = ['usuarios','titulo', 'texto', 'prioridade',
              'link_externo', 'link_video', 'link_foto']
    success_url = reverse_lazy('noticia_list')
    template_name = 'campus_app/noticia_update_form.html'


class NoticiaDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'campus_app.delete_noticia'
    model = Noticia
    success_url = reverse_lazy('noticia_list')

campus_app/templates/campus_app/base.html
<!doctype html>
{% load staticfiles %}
{% load pwa %}
{% load sass_tags %}
{% load fontawesome_5 %}
<html lang="pt">
  <head>
    {% progressive_web_app_meta %}
    {% fontawesome_5_static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Plataforma de veiculação de notícias do Campus Online" />
    <title>Campus Multiplataforma</title>
    <link href="{% sass_src 'campus_app/styles.scss' %}" rel="stylesheet" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="theme-color" content="#536878">
    <script src="https://code.jquery.com/jquery-1.8.2.js"></script>
    <script src="https://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans:300,400,500,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'campus_app/imagens/favicon-novo.ico' %}" type="image/x-icon" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-154211701-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-154211701-1');
    </script>
  </head>
  <body>
    <div class="app">
      <sidenav id="mySidenav" class="sidenav">
        <span class="closebtn" onClick={closeNav()}><i class='material-icons'>chevron_left</i></span>
        <div class="content">
          {% if user.is_authenticated %}
            <p class="login-link" id="panel-link"><a href="{% url 'dashboard' %}" class="user-link">{% fa5_icon 'grip-horizontal' 'fas' %} Painel de Controle</a></p>
            <p class="login-link" id="logout-link"><a href="{% url 'logout' %}" class="user-link">{% fa5_icon 'sign-out-alt' 'fas' %} Sair</a></p>
          {% else %}
            <p class="login-link"><a href="{% url 'login' %}" class="user-link">{% fa5_icon 'sign-in-alt' 'fas' %} Entrar</a></p>
          {% endif %}
          <p>Plataformas do Campus Online</p>
          <ul>
            <li>
              <a href="http://campus.fac.unb.br/" target="_blank" onClick={closeNav()}>{% fa5_icon 'globe' 'fas' %} Site</a>
            </li>
            <li>
              <a href="https://twitter.com/campusitounb" class="twitter" target="_blank" onClick={closeNav()}>{% fa5_icon 'twitter' 'fab' %} Twitter</a>
            </li>
            <li>
              <a href="https://www.facebook.com/onlinecampus/" class="facebook" onClick={closeNav()} target="_blank">{% fa5_icon 'facebook-square' 'fab' %} Facebook</a>
            </li>
            <li>
              <a href="https://www.instagram.com/campusonline/" class="instagram" onClick={closeNav()} target="_blank">{% fa5_icon 'instagram' 'fab' %} Instagram</a>
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UChegNOjzApuGBTQyPo3I27Q" onClick={closeNav()} target="_blank">{% fa5_icon 'youtube' 'fab' %} Youtube</a>
            </li>
            <li>
              <a href="http://wa.me/5561999915725?text=Ol%C3%A1,%20peguei%20esse%20n%C3%BAmero%20no%20App%20Campus%20Online" onClick={closeNav()} target="_blank">{% fa5_icon 'whatsapp' 'fab' %} Whatsapp</a>
            </li>
          </ul>
          <p>Links da FAC</p>
          <ul>
            <li>
              <a href="http://fac.unb.br/" onClick={closeNav()} target="_blank">{% fa5_icon 'globe' 'fas' %} Site</a>
            </li>
            <li>
              <a href="https://twitter.com/fac_unb" onClick={closeNav()} target="_blank">{% fa5_icon 'twitter' 'fab' %} Twitter</a>
            </li>
            <li>
              <a href="https://www.facebook.com/faculdadedecomunicacao/" onClick={closeNav()} target="_blank">{% fa5_icon 'facebook-square' 'fab' %} Facebook</a>
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UChJBFMMGoVw2yXeFIllVnZw" onClick={closeNav()} target="_blank">{% fa5_icon 'youtube' 'fab' %} Youtube</a>
            </li>
            <li>
              <a href="https://issuu.com/campusunb" onClick={closeNav()} target="_blank">{% fa5_icon 'link' 'fas' %} Issuu</a>
            </li>
          </ul>
        </div>
      </sidenav>
      <header>
        <script>
          function openNav() {
              var sidenav = document.getElementById("mySidenav");
              sidenav.style.display = "block";
              sidenav.style.transform = "translateX(0px)";
              sidenav.classList.add("addShadow");
              //document.getElementById("opensidenav").style.visibility = "hidden";
          }
          function closeNav() {
              var sidenav = document.getElementById("mySidenav");
              sidenav.style.transform = "translateX(-70vw)";
              sidenav.style.display = "block";
              sidenav.classList.remove("addShadow");
              //document.getElementById("opensidenav").style.visibility = "visible";
          }
          $( document ).ready(function() {
            var today = new Date()
            $("#year").text(today.getFullYear())
          })
        </script>
      </header>
      <div class="app-header">
        <span id="opensidenav" onclick="openNav()">&#9776;</span>
        <a href="{% url 'home' %}"><img src="{% static 'campus_app/imagens/Logo-Campus1.png' %}" class="app-logo" alt="logo"></a>
      </div>
      <div class="app-content">
        {% block content %}{% endblock %}
      </div>
      <footer class="footer">
        <h4><span id="year">2019</span> FAC/CIC</h4>
      </footer>
      <script>
        $(document).ready(function () {
          var header = document.getElementsByClassName("app-header")[0]
          var logo = document.getElementsByClassName("app-logo")[0]
          $(document).scroll(function() {
            if ($(document).scrollTop() < 200) {
              header.id = ""
            } else if ($(document).scrollTop() >= 200) {
              header.id = "app-header-scrolled"
            }
          })
        })
      </script>
    </div>
  </body>
</html>

campus_app/templates/campus_app/home.html
{% extends "base.html" %}

{% block content %}
  <div id="Home">
    <div class="app-content">
      <div id="calendar-region">
        <h3>
          <input class="calendar-button" type="button" id="calendario" value="{{ data | date:"d/m/Y" }}"
           onchange="requestNews()"/>
        </h3>
      </div>
      <div class="newsList">
          {% for noticia in noticias %}
            <div class="dateDivider">{{ noticia.data_publicacao | date:"d/m/Y" }}</div>
            <div class="newsContent">
              <div class="headline upper">{{ noticia.titulo }}</div>
              {% if noticia.usuarios %}
                <div class="author"><b>Por </b>
                  {% for u in noticia.usuarios.all %}
                    <spam> {{ u.first_name }} {{ u.last_name }} | </spam>
                  {% empty %}
                  {% endfor %}

                </div>
              {% endif %}
              <div class="adtInfo">
                <div class="timestamp">{{ noticia.data_publicacao | date:"d/m/Y  H:i" }}</div>
              </div>
              <div class="media">
                {% if noticia.link_video %}
                  <iframe class="newsVideo" src="{{ noticia.link_video }}"></iframe>
                  {% else %}
                    {% if noticia.link_foto %}
                      <img class="newsImg" src="{{ noticia.link_foto }}" alt="Imagem">
                    {% endif %}
                {% endif %}
              </div>
              <div class="texto">
                <p>{{ noticia.texto }}</p>
              </div>
              {% if noticia.link_externo %}
                <a class="link" href="{{ noticia.link_externo }}" target="_blank">Leia mais</a>
              {% endif %}
            </div>
          {% endfor %}
        <div class="endPage"></div>
      </div>
    </div>
    <script>
      $(function () {
        $( "#calendario" ).datepicker({
          showButtonPanel: true,
          dateFormat: 'yy/m/dd',
          changeMonth: true,
          changeYear: true,
          maxDate: 0,
          minDate: "-2y",
          currentText: "Hoje",
          closeText: "Fechar",
          dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
          dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
          dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
          monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
          monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
        });
      });
      function requestNews () {
        let url = 'http://127.0.0.1:8000/noticia_archive_day/' + document.getElementById("calendario").value;
        window.location.href = url;
      };
    </script>
  </div>
{% endblock %}

campus_app/templates/campus_app/noticia_archive_day.html
{% extends "base.html" %}

{% block content %}
  <div id="Home">
    <div class="app-content">
      <div id="calendar-region">
        <h3>
          <input class="calendar-button" type="button" id="calendario" value="{{ data | date:"d/m/Y" }}"
           onchange="requestNews()"/>
        </h3>
      </div>
      <div class="app">
        <a class="calendar-button" type="button" href="{% url 'home' %}"><b>Inicio</b></a>
      </div>
      <div class="newsList">
        <div class="newsItem">
          {% if object_list %}
            {% for noticia in object_list %}
              <div class="dateDivider">{{ noticia.data_publicacao | date:"d/m/Y" }}</div>
              <div class="headline upper">{{ noticia.titulo }}</div>
              <p>
                {% if noticia.cod_usuario.first_name %}
                  <div class="author"><b>Por {{ noticia.cod_usuario.first_name }} {{ noticia.cod_usuario.last_name }}</b></div>
                {% endif %}
                <div class="adtInfo">
                  <div class="timestamp">{{ noticia.data_publicacao | date:"d/m/Y H:i:s" }}</div>
                </div>
              </p>
              <br>
              <div class="media">
                {% if noticia.link_video %}
                  <iframe class="newsVideo" src="{{ noticia.link_video }}"></iframe>
                  {% else %}
                    {% if noticia.link_foto %}
                      <img class="newsImg" src="{{ noticia.link_foto }}">
                    {% endif %}
                {% endif %}
              </div>
              <div class="texto">
                <p>{{ noticia.texto }}</p>
              </div>
              {% if noticia.link_externo %}
                <a class="link" href="{{ noticia.link_externo }}" target="_blank"><b>Leia mais</b></a>
              {% endif %}
            {% endfor %}
          {% else %}
            <h3>Nenhuma notícia postada no dia selecionado.</h3>
          {% endif %}
        </div>
        <div style="height: 100px;"></div>
      </div>
    </div>
    <script src="http://code.jquery.com/jquery-1.8.2.js"></script>
    <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
    <script>
      $(function () {
        $( "#calendario" ).datepicker({
          showButtonPanel: true,
          dateFormat: 'yy/m/dd',
          changeMonth: true,
          changeYear: true,
          maxDate: 0,
          minDate: "-2y",
          currentText: "Hoje",
          closeText: "Fechar",
          dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
          dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
          dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
          monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
          monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
        });
      });
      function requestNews () {
        //let url = "http://" + window.location.hostname + "/noticia_archive_day/" + document.getElementById("calendario").value;
        let url = 'http://127.0.0.1:8000/noticia_archive_day/' + document.getElementById("calendario").value;
        window.location.href = url;
      };
    </script>
  </div>
{% endblock %}

campus_app/templates/campus_app/noticia_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="app">
        <p> <a class="btn" href="{% url 'noticia_list' %}">Cancelar</a> </p>
        <form method="post">
          {% csrf_token %}
          <p><b>Você está certo de que quer excluir "{{ object.titulo }}" ?</b></p>
          <input class="btn" type="submit" value="Confirmar">
        </form>
      <div style="height: 100px;"></div>
    </div>
{% endblock %}

campus_app/templates/campus_app/noticia_create_form.html
{% extends "base.html" %}

{% block content %}
    <div class="news-add">
      <h3>
        <p> <a class="btn" href='/'>Home</a> </p>
        <form method="post">{% csrf_token %}{{ form.as_p }}
          <input type="submit" value="Salvar">
        </form>
      </h3>
      <div style="height: 100px;"></div>
    </div>
{% endblock %}

campus_app/templates/campus_app/noticia_form.html
{% extends "base.html" %}
{% load fontawesome_5 %}

{% block content %}
    <div class="news-form">
        <p> <a class="back-link" href="{% url 'noticia_list' %}">{% fa5_icon 'chevron-left' 'fas' %} Voltar</a> </p>
        <form method="post">
          {% csrf_token %}
          <h3>Publicado por</h3>
          <span id="open-users" onclick="openUsers()">{% fa5_icon 'chevron-down' 'fas' %} Exibir usuários</span>
          <div id="users-container">
            {{ form.usuarios }}
          </div>
          <h3>Título</h3>
          <p>{{ form.titulo }}</p>
          <div class="error">{{ form.titulo.errors }}</div>
          <h3>Texto</h3>
          <p>{{ form.texto }}</p>
          <div class="error">{{ form.texto.errors }}</div>
          <h3>Prioridade</h3>
          <p>{{ form.prioridade }}</p>
          <div class="error">{{ form.prioridade.errors }}</div>
          <h3>Link externo</h3>
          <p>{{ form.link_externo }}</p>
          <div class="error">{{ form.link_externo.errors }}</div>
          <h3 class="link-tip">Link video</h3>
          <small>Vídeos não poderão ser exibidos na prévia, mas aparecerão normalmente na versão publicada.</small>
          <p>{{ form.link_video }}</p>
          <div class="error">{{ form.link_video.errors }}</div>
          <h3 class="link-tip">Link imagem</h3>
          <small>Caso a imagem não apareça na prévia, verifique se o link está correto.</small>
          <p>{{ form.link_foto }}</p>
          <div class="error">{{ form.link_foto.errors }}</div>
          <button class="link" type="submit">Publicar</button>
        </form>
        <h3>Prévia da Notícia:</h3>
      </div>
    <div class="preview-news">
      <div class="newsList">
        <div class="dateDivider">08/10/2088</div>
        <div class="newsContent">
          <div id="preview-titulo" class="headline upper">Título</div>
          <div class="author"><b>Por Autor</b></div>
          <div class="adtInfo">
            <div class="timestamp">08/10/2088 09h28</div>
          </div>
          <div class="media">
              <img class="newsImg" src="" alt="A imagem ou vídeo aparecerá aqui">
          </div>
          <div class="texto">
            <p id="preview-texto">Texto</p>
          </div>
            <a class="link" id="preview-link" href="" target="_blank">Leia mais</a>
        </div>
      </div>
    </div>
    <div class="endPage"></div>

    <script>
      $( document ).ready(function() {
        var titulo_input = $("#id_titulo")
        var text_input = $("#id_texto")
        var link_input = $("#id_link_externo")
        var foto_input = $("#id_link_foto")

        titulo_input.change(function() {
          $("#preview-titulo").text(titulo_input.val())
        });

        text_input.change(function() {
          $("#preview-texto").text(text_input.val())
        });

        link_input.change(function() {
          $("#preview-link").attr("href", link_input.val())
        });

        foto_input.change(function() {
          $(".newsImg").attr("src", foto_input.val())
        });

        var today = new Date()
        var time = new Date()

        today = String(today.getDate()).padStart(2, '0') + '/' + String(today.getMonth() + 1).padStart(2, '0') + '/' + today.getFullYear()
        $(".dateDivider").text(today)
        today += " " + time.getHours() + ":" + time.getMinutes()
        $(".timestamp").text(today)

      });

      function openUsers () {
        $("#users-container").slideToggle("slow")
        $("#open-users i").toggleClass("fa-chevron-down")
        $("#open-users i").toggleClass("fa-chevron-up")
      }
    </script>
{% endblock %}

campus_app/templates/campus_app/noticia_list.html
{% extends "base.html" %}

{% block content %}
  <h2 class="section-title">Notícias</h2>
  <div class="panel-links">
    <a class="link" href="{% url 'home' %}">Home</a>
    <a class="link" href="{% url 'dashboard' %}">Meu Painel</a>
    <a class="link" href="{% url 'noticia_list' %}">Notícias</a>
    {% if perms.auth.view_user %}
      <a class="link" href="{% url 'users' %}">Usuários</a>
    {% endif %}
    <a class="link" href="{% url 'edit_password' %}">Editar Senha</a>
  </div>
  <div class="news-list">
    <a class="link" href="{% url 'noticia_create_form' %}"><b>Nova Publicação</b></a>
    <hr>
    <ul>
      {% for noticia in noticias %}
          <li class="news-management">
            {% if user.is_superuser or user in noticia.usuarios.all %} 
              <a class="link-outline" href="{% url 'noticia_update_form' noticia.id %}"><b>Editar</b></a>
            {% else %}
              {% for p in perfil %}
                {% if p.name == "Editor" %}
                  <a class="link-outline" href="{% url 'noticia_update_form' noticia.id %}"><b>Editar</b></a>
                {% endif %}        
              {%endfor%}
            {% endif %}
            <span class="title"> {{ noticia.titulo }}</span>
            <p class="priority"><b>Prioridade: </b>{{ noticia.prioridade }} </p>
            <p class="date"><b>Data de publicação: </b>{{ noticia.data_publicacao }}</p>
          </li>
          <hr>
      {% endfor %}
    </ul>
  </div>
  <div style="height: 100px;"></div>
{% endblock %}

campus_app/templates/campus_app/noticia_update_form.html
{% extends "base.html" %}
{% load fontawesome_5 %}

{% block content %}
    <div class="news-form">
        <p> <a class="back-link" href="{% url 'noticia_list' %}">{% fa5_icon 'chevron-left' 'fas' %} Voltar</a> </p>
        <form method="post">
          {% csrf_token %}
          <h3>Publicado por</h3>
          <p>{{ form.usuarios }}</p>
          <h3>Título</h3>
          <p>{{ form.titulo }}</p>
          <div class="error">{{ form.titulo.errors }}</div>
          <h3>Texto</h3>
          <p>{{ form.texto }}</p>
          <div class="error">{{ form.texto.errors }}</div>
          <h3>Prioridade</h3>
          <p>{{ form.prioridade }}</p>
          <div class="error">{{ form.prioridade.errors }}</div>
          <h3>Link externo</h3>
          <p>{{ form.link_externo }}</p>
          <div class="error">{{ form.link_externo.errors }}</div>
          <h3 class="link-tip">Link video</h3>
          <small>Vídeos não poderão ser exibidos na prévia, mas aparecerão normalmente na versão publicada.</small>
          <p>{{ form.link_video }}</p>
          <div class="error">{{ form.link_video.errors }}</div>
          <h3 class="link-tip">Link imagem</h3>
          <small>Caso a imagem não apareça na prévia, verifique se o link está correto.</small>
          <p>{{ form.link_foto }}</p>
          <div class="error">{{ form.link_foto.errors }}</div>
          <button class="link" type="submit">Publicar</button>
          <a class="link-outline" href="{% url 'noticia_confirm_delete' noticia.id %}">Remover</a>
        </form>
        <h3>Prévia da Notícia:</h3>
      </div>
    <div class="preview-news">
      <div class="newsList">
        <div class="dateDivider">08/10/2088</div>
        <div class="newsContent">
          <div id="preview-titulo" class="headline upper">Título</div>
          <div class="author"><b>Por Autor</b></div>
          <div class="adtInfo">
            <div class="timestamp">08/10/2088 09h28</div>
          </div>
          <div class="media">
              <img class="newsImg" src="" alt="A imagem ou vídeo aparecerá aqui">
          </div>
          <div class="texto">
            <p id="preview-texto">Texto</p>
          </div>
            <a class="link" id="preview-link" href="" target="_blank">Leia mais</a>
        </div>
      </div>
    </div>
    <div class="endPage"></div>

    <script>
      $( document ).ready(function() {
        var titulo_input = $("#id_titulo")
        var text_input = $("#id_texto")
        var link_input = $("#id_link_externo")
        var foto_input = $("#id_link_foto")

        $("#preview-titulo").text(titulo_input.val())
        $("#preview-texto").text(text_input.val())
        $("#preview-link").attr("href", link_input.val())
        $(".newsImg").attr("src", foto_input.val())

        titulo_input.change(function() {
          $("#preview-titulo").text(titulo_input.val())
        });

        text_input.change(function() {
          $("#preview-texto").text(text_input.val())
        });

        link_input.change(function() {
          $("#preview-link").attr("href", link_input.val())
        });

        foto_input.change(function() {
          $(".newsImg").attr("src", foto_input.val())
        });

        var today = new Date()
        var time = new Date()

        today = String(today.getDate()).padStart(2, '0') + '/' + String(today.getMonth() + 1).padStart(2, '0') + '/' + today.getFullYear()
        $(".dateDivider").text(today)
        today += " " + time.getHours() + ":" + time.getMinutes()
        $(".timestamp").text(today)

      });
    </script>
{% endblock %}